telegram:
  bot:
    token: ${BOT_TOKEN:xxx}
    username: ${BOT_USERNAME:livecurrency}
    max_users: ${MAX_USERS:1}
    update_delay_in_ms: ${UPDATE_DELAY:30000}

crypto:
  url: ${CRYPTO_URL:https://api.mexc.com/api/v3/ticker/price}

server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: livecurrency

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER_USERNAME:postgres}
    password: ${DB_USER_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

      format_sql: true

    show-sql: false
logging:
  level:
    org.hibernate.SQL: info