telegram:
  bot:
    token: ${BOT_TOKEN}

spring:
  application:
    name: livecurrency

  datasource:
    url: ${DB_URL}
    username: ${DB_USER_USERNAME}
    password: ${DB_USER_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

      format_sql: true

    show-sql: true
logging:
  level:
    org.hibernate.SQL: debug